version: '3'

services:
  web:
    build: ./
    container_name: django-web
    command: daphne -b 0.0.0.0 -p 8000 project.asgi:application
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx config
    ports:
      - 80:80
    depends_on:
      - web
    restart: always

volumes:
  pgdata:
