name: Linting Changes and Deploy to AWS
on:
  push:
    branches:
      - main
env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  DJANGO_PROD_ENV: ${{ secrets.DJANGO_PROD_ENV }}

permissions: write-all

jobs:
  Deploy:
    needs: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    
    - name: Pull Recent git changes
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@43.205.226.200 'cd api && git pull origin main'

    - name: Set Django ENV
      run: |
        echo "${{ env.DJANGO_PROD_ENV }}" > .env.prod
        scp -i key.pem $(pwd)/.env.prod ubuntu@43.205.226.200:/home/ubuntu/api

    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@43.205.226.200 'docker compose -f "/home/ubuntu/api/docker-compose.prod.yml" down'

    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@43.205.226.200 'docker compose -f "/home/ubuntu/api/docker-compose.prod.yml" up -d --build'
